import type { ApiDocItem, ApiDocModule } from "@/pages/data-center/apiDocsTypes";

const makeApi = ({
  id,
  moduleKey,
  moduleName,
  levelName,
  levelDesc,
  method,
  title,
  path,
  purpose,
  requestMode,
  successReturn,
  scenario,
  authScope,
  queryParams = [],
  bodyParams = [],
  returnFields,
}: Omit<ApiDocItem, "requestExample" | "responseExample"> & { returnFields: ApiDocItem["returnFields"] }): ApiDocItem => ({
  id,
  moduleKey,
  moduleName,
  levelName,
  levelDesc,
  method,
  title,
  path,
  purpose,
  requestMode,
  successReturn,
  scenario,
  authScope,
  queryParams,
  bodyParams,
  returnFields,
  requestExample: {
    method,
    url: path,
    headers: {
      Authorization: "Bearer <token>",
      "Content-Type": "application/json",
    },
    query: Object.fromEntries(queryParams.map((field) => [field.name, `<${field.type}>`])),
    body: bodyParams.length ? Object.fromEntries(bodyParams.map((field) => [field.name, `<${field.type}>`])) : null,
  },
  responseExample: {
    code: 0,
    message: "success",
    data: {
      sample: title,
      items: [{ id: "demo_001", status: "active" }],
      total: 128,
    },
    traceId: "req_20260913_0001",
  },
});

export const apiDocModules: ApiDocModule[] = [
  {
    key: "products",
    name: "产品",
    icon: "📦",
    desc: "产品、Listing、新品测试与生命周期相关接口",
    levels: [
      {
        name: "产品管理",
        desc: "SKU基础资料、价格、成本、标签、图片、报关资料",
        apis: [
          makeApi({
            id: "products-product-management-list",
            moduleKey: "products",
            moduleName: "产品",
            levelName: "产品管理",
            levelDesc: "SKU基础资料、价格、成本、标签、图片、报关资料",
            method: "GET",
            title: "查询产品SKU列表",
            path: "/api/v1/products",
            purpose: "按 SKU 维度查询产品基础资料，用于产品管理主表、批量筛选和列表导出。",
            requestMode: "Query / 无Body",
            successReturn: "SKU、产品名称、产品等级",
            scenario: "产品管理页面进入时加载。",
            authScope: "products.product_management.view",
            bodyParams: [],
            queryParams: [
              { name: "keyword", type: "string", required: false, description: "SKU/MSKU/品名模糊搜索" },
              { name: "grade", type: "string", required: false, description: "产品等级：A/B/C/D" },
            ],
            returnFields: [
              { name: "items[].sku", type: "string", required: true, description: "SKU" },
              { name: "items[].productName", type: "string", required: true, description: "产品名称" },
            ],
          }),
          makeApi({
            id: "products-product-management-batch-search",
            moduleKey: "products",
            moduleName: "产品",
            levelName: "产品管理",
            levelDesc: "SKU基础资料、价格、成本、标签、图片、报关资料",
            method: "POST",
            title: "批量搜索 SKU",
            path: "/api/v1/products/batch-search",
            purpose: "一行一个 SKU 批量精确查询，最多 1000 行，用于快速定位产品。",
            requestMode: "无Query / Body",
            successReturn: "匹配到的产品、未匹配SKU、匹配数量",
            scenario: "产品管理搜索框点击批量搜索按钮。",
            authScope: "products.product_management.view",
            queryParams: [],
            bodyParams: [
              { name: "skus", type: "string[]", required: true, description: "SKU数组，最多1000个" },
              { name: "searchType", type: "string", required: true, description: "sku/msku/productId" },
            ],
            returnFields: [
              { name: "matched[]", type: "object", required: true, description: "匹配到的产品" },
              { name: "unmatched[]", type: "string", required: true, description: "未匹配的SKU" },
            ],
          }),
        ],
      },
      {
        name: "新品分析",
        desc: "小批量测试、市场容量、转化、毛利和扩量判断",
        apis: [
          makeApi({
            id: "products-new-product-tests",
            moduleKey: "products",
            moduleName: "产品",
            levelName: "新品分析",
            levelDesc: "小批量测试、市场容量、转化、毛利和扩量判断",
            method: "GET",
            title: "查询新品测试列表",
            path: "/api/v1/new-products/tests",
            purpose: "查询所有小批量测试新品，用于新品测试工作台。",
            requestMode: "Query / 无Body",
            successReturn: "市场容量、转化率、毛利率、系统建议",
            scenario: "新品分析主页面按测试阶段、负责人、建议动作筛选。",
            authScope: "products.new_product_analysis.view",
            bodyParams: [],
            queryParams: [{ name: "stage", type: "string", required: false, description: "测试阶段" }],
            returnFields: [{ name: "items[].recommendation", type: "string", required: true, description: "系统建议" }],
          }),
        ],
      },
    ],
  },
  {
    key: "warehouse",
    name: "仓库",
    icon: "🏭",
    desc: "库存、WFS费用、仓储费、入库运输和PMC相关接口",
    levels: [
      {
        name: "WFS费用异常",
        desc: "WFS费用多收、Case状态、追回金额和跟进记录",
        apis: [
          makeApi({
            id: "warehouse-wfs-alert-list",
            moduleKey: "warehouse",
            moduleName: "仓库",
            levelName: "WFS费用异常",
            levelDesc: "WFS费用多收、Case状态、追回金额和跟进记录",
            method: "GET",
            title: "查询WFS费用异常列表",
            path: "/api/v1/warehouse/wfs-fee-alerts",
            purpose: "按店铺、SKU、Case状态、异常原因查询WFS费用多收记录。",
            requestMode: "Query / 无Body",
            successReturn: "异常SKU、多收金额、追回金额、Case状态",
            scenario: "WFS费用异常总表加载和筛选时调用。",
            authScope: "warehouse.wfs_fee_alert.view",
            bodyParams: [],
            queryParams: [
              { name: "store", type: "string", required: false, description: "店铺" },
              { name: "caseStatus", type: "string", required: false, description: "Case状态" },
            ],
            returnFields: [
              { name: "items[].sku", type: "string", required: true, description: "异常SKU" },
              { name: "items[].overFee", type: "number", required: true, description: "多收金额" },
            ],
          }),
          makeApi({
            id: "warehouse-wfs-alert-case",
            moduleKey: "warehouse",
            moduleName: "仓库",
            levelName: "WFS费用异常",
            levelDesc: "WFS费用多收、Case状态、追回金额和跟进记录",
            method: "POST",
            title: "批量开启Case",
            path: "/api/v1/warehouse/wfs-fee-alerts/cases",
            purpose: "为未开Case的WFS费用异常批量生成Case记录。",
            requestMode: "无Query / Body",
            successReturn: "创建成功数量、失败明细",
            scenario: "运营勾选异常SKU后点击批量开Case。",
            authScope: "warehouse.wfs_fee_alert.case.create",
            queryParams: [],
            bodyParams: [{ name: "alertIds", type: "string[]", required: true, description: "WFS异常记录ID" }],
            returnFields: [{ name: "createdCount", type: "number", required: true, description: "创建成功数量" }],
          }),
        ],
      },
    ],
  },
  {
    key: "sales",
    name: "销售",
    icon: "📈",
    desc: "每日销售、订单利润、Review和补货建议相关接口",
    levels: [
      {
        name: "订单利润",
        desc: "商品ID维度利润、成本、广告费和退款",
        apis: [
          makeApi({
            id: "sales-order-profit-list",
            moduleKey: "sales",
            moduleName: "销售",
            levelName: "订单利润",
            levelDesc: "商品ID维度利润、成本、广告费和退款",
            method: "GET",
            title: "查询订单利润汇总",
            path: "/api/v1/sales/order-profit",
            purpose: "按商品ID汇总订单量、销售额、成本费用、广告费和订单利润。",
            requestMode: "Query / 无Body",
            successReturn: "商品ID、销售额、订单利润、利润率",
            scenario: "订单利润页面按日期筛选后加载。",
            authScope: "sales.order_profit.view",
            bodyParams: [],
            queryParams: [{ name: "dateRange", type: "string", required: true, description: "日期范围" }],
            returnFields: [{ name: "items[].productId", type: "string", required: true, description: "商品ID" }],
          }),
        ],
      },
    ],
  },
  {
    key: "data_center",
    name: "数据中心",
    icon: "🗄️",
    desc: "同步任务、导入导出、预警中心和API文档相关接口",
    levels: [
      {
        name: "API文档",
        desc: "接口目录、OpenAPI、错误码和权限说明",
        apis: [
          makeApi({
            id: "data-center-api-docs-list",
            moduleKey: "data_center",
            moduleName: "数据中心",
            levelName: "API文档",
            levelDesc: "接口目录、OpenAPI、错误码和权限说明",
            method: "GET",
            title: "查询接口文档矩阵",
            path: "/api/v1/data-center/api-docs",
            purpose: "按一级模块和二级业务读取接口用途、请求方式、参数、返回字段和权限Scope。",
            requestMode: "Query / 无Body",
            successReturn: "模块、接口矩阵、字段模型、权限Scope",
            scenario: "API文档页面加载和搜索时调用。",
            authScope: "data_center.api_docs.view",
            bodyParams: [],
            queryParams: [{ name: "keyword", type: "string", required: false, description: "模块/接口/Path搜索" }],
            returnFields: [{ name: "modules[]", type: "object", required: true, description: "接口模块树" }],
          }),
        ],
      },
    ],
  },
];
